import os
import re

import setuptools


def get_requirements(req_path: str) -> list[str]:
    """Read pip requirements from a text file, one package per line."""
    with open(req_path, encoding="utf8") as f:
        return f.read().splitlines()


def get_long_description():
    """Load the project README as the long description for PyPI."""
    base_dir = os.path.abspath(os.path.dirname(__file__))
    with open(os.path.join(base_dir, "README.md"), encoding="utf-8") as f:
        return f.read()


def get_version():
    """Parse the package version from voicehub/__init__.py at build time."""
    current_dir = os.path.abspath(os.path.dirname(__file__))
    version_file = os.path.join(current_dir, "voicehub", "__init__.py")
    with open(version_file, encoding="utf-8") as f:
        return re.search(r'^__version__ = [\'"]([^\'"]*)[\'"]', f.read(), re.M).group(1)


INSTALL_REQUIRES = get_requirements("requirements.txt")

EXTRAS_REQUIRE = {
    "orpheustts": ["torch", "transformers"],
    "dia": [
        "torch",
        "torchaudio",
        "safetensors",
        "descript-audiotools",
        "einops",
    ],
    "vui": [
        "torch",
        "torchaudio",
        "transformers",
        "pydantic",
        "einops",
        "inflect",
        "pyannote.audio",
    ],
    "chatterbox": [
        "torch",
        "torchaudio",
        "transformers",
        "diffusers",
        "librosa",
        "safetensors",
        "einops",
        "onnx",
        "bitstring",
        "pandas",
        "praat-parselmouth",
        "pyloudnorm",
        "PyWavelets",
        "scikit-learn",
    ],
    "kokoro": ["torch", "transformers", "misaki", "loguru"],
    "echo": ["torch", "torchaudio", "transformers", "einops"],
    "conversationtts": [
        "torch==2.5.0",
        "torchaudio",
        "torchao",
        "torchtune",
        "huggingface-hub",
        "omegaconf",
        "einops",
        "vector-quantize-pytorch",
        "peft",
    ],
    "llasa": [
        "torch",
        "torchaudio",
        "transformers",
        "einops",
        "torchtune",
        "vector-quantize-pytorch",
    ],
    "cosyvoice": [
        "torch",
        "torchaudio",
        "huggingface-hub",
        "modelscope",
        "hyperpyyaml",
        "onnxruntime",
        "transformers",
        "diffusers",
        "x-transformers",
        "einops",
        "inflect",
    ],
    "f5tts": [
        "torch",
        "torchaudio",
        "transformers",
        "cached-path",
        "hydra-core",
        "omegaconf",
        "x-transformers",
        "torchdiffeq",
        "ema-pytorch",
        "librosa",
        "pydub",
        "matplotlib",
        "einops",
        "scipy",
        "tqdm",
    ],
    "gptsovits": [
        "torch",
        "torchaudio",
        "transformers",
        "librosa",
        "ffmpeg-python",
        "peft",
        "pyyaml",
        "pytorch-lightning",
        "einops",
        "x-transformers",
        "pypinyin",
        "jieba-fast",
        "cn2an",
        "nltk",
        "soundfile",
    ],
    "melotts": [
        "torch",
        "torchaudio",
        "transformers",
        "librosa",
        "cached-path",
        "gruut",
        "gruut-ipa",
        "num2words",
        "anyascii",
        "pypinyin",
        "jieba",
    ],
    "openvoice": [
        "torch",
        "torchaudio",
        "transformers",
        "librosa",
        "faster-whisper",
        "inflect",
        "eng-to-ipa",
        "pypinyin",
        "jieba",
        "cn2an",
        "unidecode",
        "resampy",
    ],
    "outetts": [
        "torch",
        "torchaudio",
        "transformers",
        "loguru",
        "einops",
        "inflect",
        "uroman",
    ],
    "parlertts": [
        "torch",
        "transformers",
        "numpy",
        "packaging",
    ],
    "styletts2": [
        "torch",
        "torchaudio",
        "transformers",
        "librosa",
        "phonemizer",
        "nltk",
        "munch",
        "pyyaml",
        "einops",
        "einops-exts",
        "scipy",
    ],
    "mosstts": [
        "torch",
        "torchaudio",
        "transformers>=4.57",
        "accelerate",
        "safetensors",
        "librosa",
        "einops",
        "tiktoken",
        "orjson",
        "scipy",
        "tqdm",
        "pyyaml",
    ],
    "qwen3tts": [
        "torch",
        "torchaudio",
        "transformers>=4.57",
        "accelerate",
        "librosa",
        "onnxruntime",
        "einops",
    ],
    "irodoritts": [
        "torch>=2.10",
        "torchaudio>=2.10",
        "torchcodec>=0.10,<0.11",
        "transformers<5",
        "peft>=0.18",
        "safetensors>=0.7",
        "sentencepiece",
        "librosa",
        "numba",
        "pyyaml",
        "tqdm",
    ],
    "zonos": [
        "torch>=2.5",
        "torchaudio>=2.5",
        "transformers>=4.48",
        "inflect>=7.5",
        "kanjize",
        "phonemizer",
        "sudachidict-full",
        "sudachipy",
    ],
    "zonos2": [
        "torch",
        "torchaudio",
        "transformers>=4.56",
        "msgpack",
        "pyzmq",
        "apache-tvm-ffi",
        "ninja",
        "pynini",
        "regex",
        "sacremoses",
    ],
    "voxcpm": [
        "torch>=2.5",
        "torchaudio>=2.5",
        "torchcodec",
        "transformers>=4.36",
        "einops",
        "inflect",
        "addict",
        "wetext",
        "pydantic",
        "simplejson",
        "sortedcontainers",
        "librosa",
        "argbind",
        "safetensors",
    ],
    "omnivoice": [
        "torch>=2.4",
        "torchaudio>=2.4",
        "transformers>=5.3",
        "accelerate",
        "pydub",
        "librosa",
    ],
    "higgstts": [
        "torch",
        "torchaudio",
        "torchvision",
        "transformers>=4.45.1,<4.47",
        "accelerate",
        "librosa",
        "dacite",
        "json-repair",
        "pydantic",
        "vector-quantize-pytorch",
        "omegaconf",
        "langid",
        "jieba",
    ],
    "xtts": [
        "torch>=2.1",
        "torchaudio",
        "transformers>=4.33",
        "coqpit>=0.0.16",
        "librosa>=0.10",
        "scipy",
        "scikit-learn",
        "numba",
        "inflect",
        "anyascii",
        "pysbd",
        "unidecode",
        "num2words",
        "gruut[de,es,fr]",
        "jieba",
        "pypinyin",
        "hangul-romanize",
        "jamo",
        "nltk",
    ],
    "vibevoice": [
        "torch",
        "transformers>=4.51.3,<5",
        "accelerate",
        "diffusers",
        "numba",
        "scipy",
        "librosa",
        "ml-collections",
        "absl-py",
        "pydub",
    ],
    "fishtts": [
        "torch",
        "torchaudio",
        "transformers<=4.57.3",
        "hydra-core",
        "omegaconf",
        "lightning",
        "einops",
        "einx[torch]",
        "librosa",
        "natsort",
        "loguru",
        "loralib",
        "resampy",
        "ormsgpack",
        "tiktoken",
        "safetensors",
    ],
    "csm": [
        "torch",
        "torchaudio",
        "torchao",
        "torchtune",
        "tokenizers",
        "transformers",
        "sentencepiece",
        "safetensors",
    ],
    "neutts": [
        "torch>=2.8",
        "torchaudio>=2.8",
        "transformers>=5.1",
        "librosa",
        "phonemizer",
    ],
    "supertonic": [
        "onnxruntime>=1.23",
        "librosa",
        "pyyaml",
    ],
    "inflecttts": [
        "torch",
        "num2words",
        "phonemizer",
    ],
    "test": ["pre-commit", "pytest"],
}

setuptools.setup(
    name="voicehub",
    version=get_version(),
    author="kadirnardev",
    author_email="kadir.nar@hotmail.com",
    license="Apache-2.0",
    description="VoiceHub: A Unified Inference Interface for TTS Models",
    long_description=get_long_description(),
    long_description_content_type="text/markdown",
    url="https://github.com/kadirnar/voicehub",
    install_requires=INSTALL_REQUIRES,
    extras_require=EXTRAS_REQUIRE,
    python_requires=">=3.10",
    packages=setuptools.find_packages(exclude=("tests", "tests.*")),
    include_package_data=True,
)
