"""Optional custom kernels with portable PyTorch fallbacks.

Importing this package never imports Triton, initializes CUDA, or
invokes a compiler. Accelerator backends are selected lazily from
concrete tensor arguments, and CUDA source compilation requires an
explicit loader call.
"""

from voicehub.kernels.activations import (
    ACTIVATION_CUDA_EXTENSION_NAME,
    AUDIO_CODEC_SNAKE,
    AUDIO_CODEC_SNAKE_BETA,
    DIFFUSION_FUSED_BIAS_GELU,
    DIFFUSION_FUSED_MODULATE,
    LLM_GATED_SILU,
    VITS_FUSED_ADD_TANH_SIGMOID,
    VITS_TANH_SIGMOID_GATE,
    codec_snake,
    codec_snake_beta,
    codec_snake_beta_reference,
    codec_snake_reference,
    fused_add_tanh_sigmoid,
    fused_add_tanh_sigmoid_reference,
    fused_bias_gelu,
    fused_bias_gelu_reference,
    fused_modulate,
    fused_modulate_reference,
    gated_silu,
    gated_silu_reference,
    load_tts_activation_cuda_extension,
    tanh_sigmoid_gate,
    tanh_sigmoid_gate_reference,
)
from voicehub.kernels.capabilities import (
    CapabilityStatus,
    KernelCapabilities,
    cuda_extension_capability,
    cuda_runtime_capability,
    get_kernel_capabilities,
    triton_capability,
)
from voicehub.kernels.codecs import CodecSnakeBetaKernelOptimizable, CodecSnakeKernelOptimizable
from voicehub.kernels.cuda_extensions import (
    CUDA_EXTENSIONS,
    CudaExtensionBuildError,
    CudaExtensionError,
    CudaExtensionRegistry,
    CudaExtensionSpec,
    CudaExtensionUnavailableError,
    LoadedCudaExtension,
    load_cuda_extension,
    register_cuda_extension,
)
from voicehub.kernels.diffusion import DiffusionModulationKernelOptimizable
from voicehub.kernels.registry import (
    KERNEL_REGISTRY,
    KernelBackend,
    KernelDispatchError,
    KernelError,
    KernelRegistrationError,
    KernelRegistry,
    KernelSupport,
    RegisteredKernel,
    dispatch_kernel,
    register_kernel,
    resolve_kernel,
)
from voicehub.kernels.vits import VITSKernelOptimizable

__all__ = [
    "ACTIVATION_CUDA_EXTENSION_NAME",
    "AUDIO_CODEC_SNAKE",
    "AUDIO_CODEC_SNAKE_BETA",
    "CUDA_EXTENSIONS",
    "CapabilityStatus",
    "CudaExtensionBuildError",
    "CudaExtensionError",
    "CudaExtensionRegistry",
    "CudaExtensionSpec",
    "CudaExtensionUnavailableError",
    "DIFFUSION_FUSED_BIAS_GELU",
    "DIFFUSION_FUSED_MODULATE",
    "DiffusionModulationKernelOptimizable",
    "KERNEL_REGISTRY",
    "KernelBackend",
    "KernelCapabilities",
    "KernelDispatchError",
    "KernelError",
    "KernelRegistry",
    "KernelRegistrationError",
    "KernelSupport",
    "LLM_GATED_SILU",
    "LoadedCudaExtension",
    "CodecSnakeKernelOptimizable",
    "CodecSnakeBetaKernelOptimizable",
    "RegisteredKernel",
    "VITS_FUSED_ADD_TANH_SIGMOID",
    "VITS_TANH_SIGMOID_GATE",
    "VITSKernelOptimizable",
    "cuda_extension_capability",
    "cuda_runtime_capability",
    "dispatch_kernel",
    "codec_snake",
    "codec_snake_beta",
    "codec_snake_beta_reference",
    "codec_snake_reference",
    "fused_add_tanh_sigmoid",
    "fused_add_tanh_sigmoid_reference",
    "fused_bias_gelu",
    "fused_bias_gelu_reference",
    "fused_modulate",
    "fused_modulate_reference",
    "gated_silu",
    "gated_silu_reference",
    "get_kernel_capabilities",
    "load_cuda_extension",
    "load_tts_activation_cuda_extension",
    "register_cuda_extension",
    "register_kernel",
    "resolve_kernel",
    "tanh_sigmoid_gate",
    "tanh_sigmoid_gate_reference",
    "triton_capability",
]
