"""Dependency-light language support metadata for model documentation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from voicehub.tasks import SpeechTask

LanguageSupportKind = Literal["enumerated", "not-text-conditioned"]


@dataclass(frozen=True, slots=True)
class ModelLanguageSupport:
    """Describe the language boundary that VoiceHub can document safely."""

    kind: LanguageSupportKind
    codes: tuple[str, ...] = ()
    note: str | None = None

    def __post_init__(self) -> None:
        if self.kind == "enumerated" and not self.codes:
            raise ValueError("Enumerated language support requires at least one language code.")
        if self.kind != "enumerated" and self.codes:
            raise ValueError(f"{self.kind!r} language support must not declare language codes.")
        if any(not isinstance(code, str) or not code.strip() for code in self.codes):
            raise ValueError("Language codes must be non-empty strings.")
        normalized = tuple(code.strip() for code in self.codes)
        if len(normalized) != len(set(normalized)):
            raise ValueError("Language codes must not contain duplicates.")
        object.__setattr__(self, "codes", normalized)
        if self.note is not None and (not isinstance(self.note, str) or not self.note.strip()):
            raise ValueError("A language-support note must be a non-empty string or None.")


_ENUMERATED_LANGUAGE_CODES = {
    "orpheustts": ("en", ),
    "dia": ("en", ),
    "vui": ("en", ),
    "chatterbox": (
        "ar",
        "da",
        "de",
        "el",
        "en",
        "es",
        "fi",
        "fr",
        "he",
        "hi",
        "it",
        "ja",
        "ko",
        "ms",
        "nl",
        "no",
        "pl",
        "pt",
        "ru",
        "sv",
        "sw",
        "tr",
        "zh",
    ),
    "kokoro": ("en-US", "en-GB", "es", "fr", "hi", "it", "pt-BR", "ja", "zh"),
    "echo": ("en", ),
    "conversationtts": ("en", "zh", "yue"),
    "llasa": ("zh", "en", "de", "fr", "ja", "ko", "nl", "es", "it", "pt", "pl"),
    "cosyvoice": ("zh", "en", "ja", "ko", "de", "es", "fr", "it", "ru"),
    "f5tts": ("en", "zh"),
    "gptsovits": ("zh", "en", "ja", "ko", "yue"),
    "melotts": ("en", "fr", "ja", "es", "zh", "ko"),
    "openvoice": ("en", "es", "fr", "zh", "ja", "ko"),
    "outetts": (
        "en",
        "ar",
        "zh",
        "nl",
        "fr",
        "de",
        "it",
        "ja",
        "ko",
        "lt",
        "ru",
        "es",
        "pt",
        "be",
        "bn",
        "ka",
        "hu",
        "lv",
        "fa",
        "pl",
        "sw",
        "ta",
        "uk",
    ),
    "parlertts": ("en", ),
    "styletts2": ("en-US", ),
    "mosstts": (
        "zh",
        "yue",
        "en",
        "ar",
        "cs",
        "da",
        "de",
        "nl",
        "es",
        "fr",
        "fi",
        "el",
        "he",
        "hi",
        "hu",
        "ja",
        "it",
        "ko",
        "mk",
        "ms",
        "ru",
        "fa",
        "pl",
        "pt",
        "sv",
        "ro",
        "sw",
        "tl",
        "th",
        "tr",
        "vi",
    ),
    "qwen3tts": ("zh", "en", "ja", "ko", "de", "fr", "ru", "pt", "es", "it"),
    "irodoritts": ("ja", ),
    "zonos": ("en", "ja", "zh", "fr", "de"),
    "zonos2": (
        "en",
        "zh",
        "ja",
        "ko",
        "ru",
        "it",
        "pt",
        "fr",
        "es",
        "vi",
        "de",
        "he",
        "nl",
        "sv",
        "hi",
        "ta",
        "te",
        "th",
        "no",
        "bn",
        "tl",
        "ar",
        "da",
        "id",
        "pl",
        "uk",
        "ro",
        "fi",
        "hu",
        "lt",
        "et",
        "sk",
        "hr",
        "lv",
    ),
    "voxcpm": (
        "zh",
        "en",
        "ar",
        "my",
        "da",
        "nl",
        "fi",
        "fr",
        "de",
        "el",
        "he",
        "hi",
        "id",
        "it",
        "ja",
        "km",
        "ko",
        "lo",
        "ms",
        "no",
        "pl",
        "pt",
        "ru",
        "es",
        "sw",
        "sv",
        "tl",
        "th",
        "tr",
        "vi",
    ),
    "higgstts": ("en", "zh", "de", "ko"),
    "xtts": (
        "en",
        "es",
        "fr",
        "de",
        "it",
        "pt",
        "pl",
        "tr",
        "ru",
        "nl",
        "cs",
        "ar",
        "zh-CN",
        "hu",
        "ko",
        "ja",
        "hi",
    ),
    "vibevoice": ("en", ),
    "fishtts": (
        "zh",
        "en",
        "ja",
        "ko",
        "es",
        "pt",
        "ar",
        "ru",
        "fr",
        "de",
        "sv",
        "it",
        "tr",
        "no",
        "nl",
        "cy",
        "eu",
        "ca",
        "da",
        "gl",
        "ta",
        "hu",
        "fi",
        "pl",
        "et",
        "hi",
        "la",
        "ur",
        "th",
        "vi",
        "jw",
        "bn",
        "yo",
        "sl",
        "cs",
        "sw",
        "nn",
        "he",
        "ms",
        "uk",
        "id",
        "kk",
        "bg",
        "lv",
        "my",
        "tl",
        "sk",
        "ne",
        "fa",
        "af",
        "el",
        "bo",
        "hr",
        "ro",
        "sn",
        "mi",
        "yi",
        "am",
        "be",
        "km",
        "is",
        "az",
        "sd",
        "br",
        "sq",
        "ps",
        "mn",
        "ht",
        "ml",
        "sr",
        "sa",
        "te",
        "ka",
        "bs",
        "pa",
        "lt",
        "kn",
        "si",
        "hy",
        "mr",
        "as",
        "gu",
        "fo",
    ),
    "csm": ("en", ),
    "neutts": ("en", ),
    "supertonic": (
        "en",
        "ko",
        "ja",
        "ar",
        "bg",
        "cs",
        "da",
        "de",
        "el",
        "es",
        "et",
        "fi",
        "fr",
        "hi",
        "hr",
        "hu",
        "id",
        "it",
        "lt",
        "lv",
        "nl",
        "pl",
        "pt",
        "ro",
        "ru",
        "sk",
        "sl",
        "sv",
        "tr",
        "uk",
        "vi",
    ),
    "inflecttts": ("en-US", ),
    "bark": ("de", "en", "es", "fr", "hi", "it", "ja", "ko", "pl", "pt", "ru", "tr", "zh"),
    "speecht5": ("en", ),
    "vits": ("en", ),
    "asr_tiron": ("en", "zh"),
    "asr_vibevoice": (
        "en",
        "zh",
        "es",
        "pt",
        "de",
        "ja",
        "ko",
        "fr",
        "ru",
        "id",
        "sv",
        "it",
        "he",
        "nl",
        "pl",
        "no",
        "tr",
        "th",
        "ar",
        "hu",
        "ca",
        "cs",
        "da",
        "fa",
        "af",
        "hi",
        "fi",
        "et",
        "aa",
        "el",
        "ro",
        "vi",
        "bg",
        "is",
        "sl",
        "sk",
        "lt",
        "sw",
        "uk",
        "kl",
        "lv",
        "hr",
        "ne",
        "sr",
        "tl",
        "yi",
        "ms",
        "ur",
        "mn",
        "hy",
        "jv",
    ),
    "asr_granite_speech": ("en", "fr", "de", "es", "pt", "ja"),
    "asr_parakeet_tdt": (
        "en",
        "es",
        "fr",
        "de",
        "bg",
        "hr",
        "cs",
        "da",
        "nl",
        "et",
        "fi",
        "el",
        "hu",
        "it",
        "lv",
        "lt",
        "mt",
        "pl",
        "pt",
        "ro",
        "sk",
        "sl",
        "sv",
        "ru",
        "uk",
    ),
    "asr_nemotron": (
        "en-US",
        "en-GB",
        "es-US",
        "es-ES",
        "fr-FR",
        "fr-CA",
        "it-IT",
        "pt-BR",
        "pt-PT",
        "nl-NL",
        "de-DE",
        "tr-TR",
        "ru-RU",
        "ar-AR",
        "hi-IN",
        "ja-JP",
        "ko-KR",
        "vi-VN",
        "uk-UA",
        "pl-PL",
        "sv-SE",
        "cs-CZ",
        "nb-NO",
        "da-DK",
        "bg-BG",
        "fi-FI",
        "hr-HR",
        "sk-SK",
        "zh-CN",
        "hu-HU",
        "ro-RO",
        "et-EE",
        "el-GR",
        "lt-LT",
        "lv-LV",
        "mt-MT",
        "sl-SI",
        "he-IL",
        "th-TH",
        "nn-NO",
    ),
    "asr_wav2vec2": ("en", ),
    "asr_hubert": ("en", ),
    "asr_wavlm": ("en", ),
    "asr_medasr": ("en", ),
    "asr_moonshine": ("en", ),
    "asr_nemo": ("en", ),
    "asr_speechbrain": ("en", ),
    "asr_funasr": ("zh", "en", "ja", "ko", "yue"),
    "asr_espnet": ("en", ),
    "asr_wenet": ("en", ),
}

_LANGUAGE_NOTES = {
    "echo": (
        "The release card and reference implementation demonstrate English prompts and do not claim "
        "broader language coverage."),
    "conversationtts":
    ("These are the languages explicitly named in the upstream release README's podcast data."),
    "cosyvoice": (
        "The card additionally names Guangdong, Minnan, Sichuan, Dongbei, Shan3xi, Shan1xi, Shanghai, "
        "Tianjin, Shandong, Ningxia, and Gansu Chinese dialects or accents."),
    "gptsovits":
    "Korean and Cantonese support applies to V2 and later variants.",
    "asr_granite_speech":
    ("These are ASR input languages; Italian and Mandarin are documented as translation targets only."),
    "asr_nemotron": (
        "The `el-GR`, `lt-LT`, `lv-LV`, `mt-MT`, `sl-SI`, `he-IL`, `th-TH`, and `nn-NO` locales "
        "are adaptation-ready and require in-domain fine-tuning; the other listed locales are "
        "transcription-ready or broad-coverage."),
    "asr_qwen3": (
        "The same checkpoint also names Anhui, Dongbei, Fujian, Gansu, Guizhou, Hebei, Henan, Hubei, "
        "Hunan, Jiangxi, Ningxia, Shandong, Shaanxi, Shanxi, Sichuan, Tianjin, Yunnan, Zhejiang, "
        "Cantonese (Hong Kong accent), Cantonese (Guangdong accent), Wu, and Minnan dialects."),
}

_WHISPER_MODEL_TYPES = frozenset({
    "asr_transformers",
    "asr_faster_whisper",
    "asr_openai_whisper",
    "asr_whisper",
    "asr_whisperx",
})


def model_language_support(spec) -> ModelLanguageSupport:
    """Return documented language support without importing a model backend."""
    model_type = spec.model_type
    if model_type in _ENUMERATED_LANGUAGE_CODES:
        return ModelLanguageSupport(
            "enumerated",
            _ENUMERATED_LANGUAGE_CODES[model_type],
            _LANGUAGE_NOTES.get(model_type),
        )
    if model_type in _WHISPER_MODEL_TYPES:
        from voicehub.architectures.whisper.tokenization import LANGUAGES

        # The tokenizer recognizes Cantonese, but the default OpenAI checkpoint
        # cards enumerate the other language abbreviations only.
        codes = tuple(code for code in LANGUAGES if code != "yue")
        return ModelLanguageSupport("enumerated", codes)
    if model_type == "omnivoice":
        from voicehub.architectures.omnivoice.languages import OMNIVOICE_LANGUAGE_CODES

        return ModelLanguageSupport("enumerated", OMNIVOICE_LANGUAGE_CODES)
    if model_type == "asr_qwen3":
        from voicehub.architectures.qwen3_asr.languages import LANGUAGE_CODES

        return ModelLanguageSupport(
            "enumerated",
            tuple(LANGUAGE_CODES),
            _LANGUAGE_NOTES[model_type],
        )
    if model_type == "asr_cohere":
        from voicehub.architectures.cohere_asr.configuration import SUPPORTED_LANGUAGES

        return ModelLanguageSupport("enumerated", tuple(SUPPORTED_LANGUAGES))
    if model_type == "asr_seamless_m4t_v2":
        from voicehub.architectures.seamless_m4t_v2.languages import SEAMLESS_M4T_V2_LANGUAGE_TO_ID

        return ModelLanguageSupport(
            "enumerated",
            tuple(SEAMLESS_M4T_V2_LANGUAGE_TO_ID),
            "These are output-language prompts supported by the audited S2T checkpoint.",
        )
    if spec.task is SpeechTask.VOICE_ACTIVITY_DETECTION:
        return ModelLanguageSupport(
            "not-text-conditioned",
            note=(
                "The public VAD contract does not select a spoken language; validate checkpoint "
                "acoustic coverage on the target languages and recording conditions."),
        )
    raise ValueError(
        f"Model {model_type!r} must declare every supported language abbreviation before its "
        "documentation can be generated.")


__all__ = ["LanguageSupportKind", "ModelLanguageSupport", "model_language_support"]
