"""Model-family training adapters for every registered VoiceHub backend."""

from voicehub.training.adapters import (
    AcousticTrainingAdapter,
    AudioClassificationTrainingAdapter,
    BaseTrainingAdapter,
    CausalLMTrainingAdapter,
    CompositeTrainingAdapter,
    CTCTrainingAdapter,
    FlowMatchingTrainingAdapter,
    FrameClassificationTrainingAdapter,
    RNNTTrainingAdapter,
    Seq2SeqTrainingAdapter,
    SpeechSeq2SeqTrainingAdapter,
    TDTTrainingAdapter,
    UpstreamNativeTrainingAdapter,
    VITSTrainingAdapter,
)
from voicehub.training.auto import AutoTrainingAdapter
from voicehub.training.collators import (
    AudioFieldSchema,
    DataCollatorForAudioTraining,
    DataCollatorForTTSTraining,
    TTSFieldSchema,
)
from voicehub.training.contracts import (
    TrainingContext,
    TrainingPhaseKind,
    TrainingPhaseSpec,
    TrainingRecipeKind,
    TrainingSupport,
)
from voicehub.training.datasets import SpeechDataset
from voicehub.training.optimization import OptimizerBundle, SchedulerBundle
from voicehub.training.specs import (
    ALL_MODEL_TRAINING_SPECS,
    MODEL_TRAINING_SPECS,
    ModelTrainingSpec,
    TrainingFamily,
    get_training_spec,
    list_training_specs,
    register_training_alias,
    register_training_spec,
    unregister_training_alias,
    unregister_training_spec,
)
from voicehub.training.strategy import (
    TorchTrainingStrategy,
    TrainingStrategy,
    get_training_strategy,
    list_training_strategies,
    register_training_strategy,
    unregister_training_strategy,
)

__all__ = [
    "AcousticTrainingAdapter",
    "AudioClassificationTrainingAdapter",
    "AudioFieldSchema",
    "ALL_MODEL_TRAINING_SPECS",
    "AutoTrainingAdapter",
    "BaseTrainingAdapter",
    "CausalLMTrainingAdapter",
    "CompositeTrainingAdapter",
    "CTCTrainingAdapter",
    "DataCollatorForAudioTraining",
    "DataCollatorForTTSTraining",
    "FlowMatchingTrainingAdapter",
    "FrameClassificationTrainingAdapter",
    "MODEL_TRAINING_SPECS",
    "ModelTrainingSpec",
    "OptimizerBundle",
    "RNNTTrainingAdapter",
    "Seq2SeqTrainingAdapter",
    "SchedulerBundle",
    "SpeechSeq2SeqTrainingAdapter",
    "SpeechDataset",
    "TDTTrainingAdapter",
    "TrainingFamily",
    "TrainingContext",
    "TrainingPhaseKind",
    "TrainingPhaseSpec",
    "TrainingRecipeKind",
    "TrainingStrategy",
    "TrainingSupport",
    "TTSFieldSchema",
    "TorchTrainingStrategy",
    "UpstreamNativeTrainingAdapter",
    "VITSTrainingAdapter",
    "get_training_strategy",
    "get_training_spec",
    "list_training_strategies",
    "list_training_specs",
    "register_training_alias",
    "register_training_spec",
    "register_training_strategy",
    "unregister_training_alias",
    "unregister_training_spec",
    "unregister_training_strategy",
]
