"""Pinned provenance for the VoiceHub-native SpeechT5 architecture."""

from __future__ import annotations

from types import MappingProxyType

from voicehub.models.speecht5.metadata import (
    NATIVE_SPEECHT5_FORMAT,
    SPEECHT5_ASSET_SHA256,
    SPEECHT5_CHECKPOINT_FILENAME,
    SPEECHT5_CHECKPOINT_SHA256,
    SPEECHT5_CHECKPOINT_SIZE,
    SPEECHT5_HIFIGAN_CHECKPOINT_FILENAME,
    SPEECHT5_HIFIGAN_CHECKPOINT_SHA256,
    SPEECHT5_HIFIGAN_CHECKPOINT_SIZE,
    SPEECHT5_HIFIGAN_CONFIG_SHA256,
    SPEECHT5_HIFIGAN_REPOSITORY,
    SPEECHT5_HIFIGAN_REVISION,
    SPEECHT5_HIFIGAN_STATE_VALUES,
    SPEECHT5_HIFIGAN_TENSOR_COUNT,
    SPEECHT5_HIFIGAN_TENSOR_FINGERPRINT,
    SPEECHT5_REPOSITORY,
    SPEECHT5_REVISION,
    SPEECHT5_STATE_VALUES,
    SPEECHT5_TENSOR_COUNT,
    SPEECHT5_TENSOR_FINGERPRINT,
    TRANSFORMERS_REFERENCE_REVISION,
    TRANSFORMERS_REFERENCE_TAG,
)

SPEECHT5_SOURCE_REPOSITORY = "https://github.com/huggingface/transformers"
SPEECHT5_SOURCE_REVISION = TRANSFORMERS_REFERENCE_REVISION
SPEECHT5_SOURCE_TAG = TRANSFORMERS_REFERENCE_TAG
SPEECHT5_SOURCE_LICENSE = "Apache-2.0"
SPEECHT5_CHECKPOINT_LICENSE = "MIT"
SPEECHT5_HIFIGAN_CHECKPOINT_LICENSE = "MIT"

SPEECHT5_SOURCE_FILES = (
    "src/transformers/models/speecht5/configuration_speecht5.py",
    "src/transformers/models/speecht5/feature_extraction_speecht5.py",
    "src/transformers/models/speecht5/modeling_speecht5.py",
    "src/transformers/models/speecht5/processing_speecht5.py",
    "src/transformers/models/speecht5/tokenization_speecht5.py",
)

SPEECHT5_REFERENCE_INVENTORY = MappingProxyType({
    "repository": SPEECHT5_REPOSITORY,
    "revision": SPEECHT5_REVISION,
    "filename": SPEECHT5_CHECKPOINT_FILENAME,
    "license": SPEECHT5_CHECKPOINT_LICENSE,
    "sha256": SPEECHT5_CHECKPOINT_SHA256,
    "size": SPEECHT5_CHECKPOINT_SIZE,
    "tensor_count": SPEECHT5_TENSOR_COUNT,
    "state_values": SPEECHT5_STATE_VALUES,
    "tensor_inventory_fingerprint": SPEECHT5_TENSOR_FINGERPRINT,
})

SPEECHT5_HIFIGAN_REFERENCE_INVENTORY = MappingProxyType({
    "repository":
    SPEECHT5_HIFIGAN_REPOSITORY,
    "revision":
    SPEECHT5_HIFIGAN_REVISION,
    "filename":
    SPEECHT5_HIFIGAN_CHECKPOINT_FILENAME,
    "license":
    SPEECHT5_HIFIGAN_CHECKPOINT_LICENSE,
    "sha256":
    SPEECHT5_HIFIGAN_CHECKPOINT_SHA256,
    "size":
    SPEECHT5_HIFIGAN_CHECKPOINT_SIZE,
    "tensor_count":
    SPEECHT5_HIFIGAN_TENSOR_COUNT,
    "state_values":
    SPEECHT5_HIFIGAN_STATE_VALUES,
    "tensor_inventory_fingerprint":
    SPEECHT5_HIFIGAN_TENSOR_FINGERPRINT,
})

SPEECHT5_PROCESSOR_INTEGRITY = MappingProxyType(dict(SPEECHT5_ASSET_SHA256))

__all__ = [
    "NATIVE_SPEECHT5_FORMAT",
    "SPEECHT5_CHECKPOINT_LICENSE",
    "SPEECHT5_HIFIGAN_CHECKPOINT_LICENSE",
    "SPEECHT5_HIFIGAN_CONFIG_SHA256",
    "SPEECHT5_HIFIGAN_REFERENCE_INVENTORY",
    "SPEECHT5_PROCESSOR_INTEGRITY",
    "SPEECHT5_REFERENCE_INVENTORY",
    "SPEECHT5_SOURCE_FILES",
    "SPEECHT5_SOURCE_LICENSE",
    "SPEECHT5_SOURCE_REPOSITORY",
    "SPEECHT5_SOURCE_REVISION",
    "SPEECHT5_SOURCE_TAG",
]
