"""Pinned provenance for the native ConversationTTS runtime."""

from __future__ import annotations

CONVERSATIONTTS_SOURCE_REPOSITORY = ("https://github.com/Audio-Foundation-Models/ConversationTTS")
CONVERSATIONTTS_SOURCE_REVISION = ("b3851f70c2dc0d35ba609734b08915637fe2a733")
CONVERSATIONTTS_LICENSE = "CC-BY-NC-4.0"

CONVERSATIONTTS_CHECKPOINT_REPOSITORY = ("AudioFoundation/SpeechFoundation")
CONVERSATIONTTS_CHECKPOINT_REVISION = ("b0f6f30e123da06dd15672ddbfc7781b323ea599")
CONVERSATIONTTS_CHECKPOINT_FILENAME = "ckpt1.checkpoint"
CONVERSATIONTTS_CHECKPOINT_SHA256 = ("dd07c77d105c8a3e69cd06e2df8dc343bea15aef4b38e3a2308b8aad0818075c")
CONVERSATIONTTS_CHECKPOINT_SIZE = 9_317_019_762

CONVERSATIONTTS_MIMI_REPOSITORY = "kyutai/moshika-pytorch-bf16"
CONVERSATIONTTS_MIMI_REVISION = ("a0870f178898fba98afe5ef08f0bdd2773d80f62")
CONVERSATIONTTS_MIMI_FILENAME = ("tokenizer-e351c8d8-checkpoint125.safetensors")

NATIVE_CONVERSATIONTTS_FORMAT = "voicehub-conversationtts-v1"

__all__ = [
    "CONVERSATIONTTS_CHECKPOINT_FILENAME",
    "CONVERSATIONTTS_CHECKPOINT_REPOSITORY",
    "CONVERSATIONTTS_CHECKPOINT_REVISION",
    "CONVERSATIONTTS_CHECKPOINT_SHA256",
    "CONVERSATIONTTS_CHECKPOINT_SIZE",
    "CONVERSATIONTTS_LICENSE",
    "CONVERSATIONTTS_MIMI_FILENAME",
    "CONVERSATIONTTS_MIMI_REPOSITORY",
    "CONVERSATIONTTS_MIMI_REVISION",
    "CONVERSATIONTTS_SOURCE_REPOSITORY",
    "CONVERSATIONTTS_SOURCE_REVISION",
    "NATIVE_CONVERSATIONTTS_FORMAT",
]
