__version__ = "0.3.0"

from importlib import import_module

from voicehub.audio import AudioInput, load_audio
from voicehub.audio_modeling_utils import PreTrainedASRModel, PreTrainedAudioModel, PreTrainedVADModel
from voicehub.auto import (
    AutoConfig,
    AutoModelForSpeechRecognition,
    AutoModelForTextToSpeech,
    AutoModelForVoiceActivityDetection,
    AutoProcessor,
)
from voicehub.automodel import AutoInferenceModel
from voicehub.configuration_utils import VoiceHubConfig
from voicehub.data_collator import DefaultDataCollator, default_data_collator
from voicehub.errors import (
    LLMBackendCompatibilityError,
    LLMBackendError,
    LLMBackendRequestError,
    OptionalDependencyError,
    SourceLicenseError,
    UnknownModelError,
    VoiceHubError,
)
from voicehub.generation_configuration import TTSGenerationConfig
from voicehub.inference_configuration import ASRInferenceConfig, SpeechInferenceConfig, VADInferenceConfig
from voicehub.inference_strategy import (
    EagerInferenceStrategy,
    InferenceStrategy,
    TorchCompileInferenceStrategy,
    get_inference_strategy,
    list_inference_strategies,
    register_inference_strategy,
    unregister_inference_strategy,
)
from voicehub.integrations import WandbCallback
from voicehub.llm_serving import (
    LLMBackend,
    LLMBackendConfig,
    LLMBackendSupport,
    LLMBackendTransport,
    TokenGenerationRequest,
    TokenGenerationResult,
    get_llm_backend_support,
    list_llm_backend_support,
)
from voicehub.modeling_outputs import (
    ASROutput,
    ASRSegment,
    ASRWord,
    SpeechSegment,
    SpeechTrainingOutput,
    TTSOutput,
    TTSTrainingOutput,
    VADOutput,
    VADSegment,
)
from voicehub.modeling_utils import PreTrainedSpeechModel, PreTrainedTTSModel
from voicehub.optimization import (
    OptimizationCompileTarget,
    OptimizationCompileTargetProvider,
    OptimizationModuleRoot,
    OptimizationModuleRootProvider,
    OptimizationRuntimeProtocol,
    TTSAttentionImplementation,
    TTSCompilePolicy,
    TTSKernelBackend,
    TTSOptimizationCompatibilityError,
    TTSOptimizationConfig,
    TTSOptimizationDecision,
    TTSOptimizationPlan,
    TTSOptimizationResult,
    TTSOptimizationSupport,
    VITSArchitectureKind,
    VITSModelOptimizationSupport,
    get_tts_optimization_config,
    get_tts_optimization_support,
    get_vits_model_optimization_support,
    list_tts_optimization_support,
    list_vits_model_optimization_support,
    resolve_tts_optimization,
)
from voicehub.policies import ModelLicenseSpec
from voicehub.processing_utils import AudioProcessor, BatchFeature, VoiceHubProcessor
from voicehub.registry import (
    ModelSpec,
    get_model_spec,
    list_model_specs,
    register_model_alias,
    register_model_spec,
    unregister_model_alias,
    unregister_model_spec,
)
from voicehub.tasks import SpeechTask
from voicehub.trainer import Trainer
from voicehub.trainer_callback import EarlyStoppingCallback, TrainerCallback, TrainerControl, TrainerState
from voicehub.trainer_utils import (
    EvalPrediction,
    IntervalStrategy,
    PredictionOutput,
    SchedulerType,
    TrainOutput,
    get_last_checkpoint,
    set_seed,
)
from voicehub.training import (
    ALL_MODEL_TRAINING_SPECS,
    AcousticTrainingAdapter,
    ASRDataArchitecture,
    ASRDataReadiness,
    ASRDataset,
    ASRDatasetSpec,
    ASRRecordVariant,
    AudioClassificationTrainingAdapter,
    AudioFieldSchema,
    AutoTrainingAdapter,
    BaseTrainingAdapter,
    CausalLMTrainingAdapter,
    CompositeTrainingAdapter,
    CTCTrainingAdapter,
    DataCollatorForAudioTraining,
    DataCollatorForTTSTraining,
    DiffusionTrainingPair,
    DiffusionTTSOptimizationConfig,
    EpochGroupedBatchSampler,
    EpochLengthBatchSampler,
    FlowMatchingTrainingAdapter,
    FrameClassificationTrainingAdapter,
    LLMTTSOptimizationConfig,
    ModelTrainingSpec,
    OptimizerBundle,
    RNNTTrainingAdapter,
    SchedulerBundle,
    Seq2SeqTrainingAdapter,
    SpeechDataset,
    SpeechSeq2SeqTrainingAdapter,
    TDTTrainingAdapter,
    TorchTrainingStrategy,
    TrainingContext,
    TrainingFamily,
    TrainingPhaseKind,
    TrainingPhaseSpec,
    TrainingRecipeKind,
    TrainingStrategy,
    TrainingSupport,
    TTSBatchingConfig,
    TTSBatchingStrategy,
    TTSDataArchitecture,
    TTSDataReadiness,
    TTSDataset,
    TTSDatasetSpec,
    TTSFieldSchema,
    TTSOptimizationProfile,
    TTSRecordVariant,
    TTSTrainingOptimizationProfile,
    UpstreamNativeTrainingAdapter,
    VITSCUDAGraphPolicy,
    VITSDiscriminatorLoss,
    VITSOptimizationConfig,
    VITSTrainingAdapter,
    build_diffusion_training_pair,
    build_flow_matching_training_pair,
    diffusion_tts_acceleration_plan,
    get_asr_dataset_spec,
    get_training_spec,
    get_training_strategy,
    get_tts_dataset_spec,
    get_tts_training_optimization_profile,
    list_asr_dataset_specs,
    list_training_specs,
    list_training_strategies,
    list_tts_dataset_specs,
    llm_tts_acceleration_plan,
    masked_diffusion_regression_loss,
    multi_codebook_cross_entropy,
    register_training_alias,
    register_training_spec,
    register_training_strategy,
    unregister_training_alias,
    unregister_training_spec,
    unregister_training_strategy,
    vits_acceleration_plan,
    vits_discriminator_loss,
    vits_feature_matching_loss,
    vits_generator_adversarial_loss,
    vits_kl_loss,
)
from voicehub.training_args import TrainingArguments

_LAZY_ROOT_EXPORTS = {
    "AudioAutoencoderView": "voicehub.components.audio.codecs",
    "AudioCodec": "voicehub.components.audio.codecs",
    "AudioCodecComponentView": "voicehub.components.audio.codecs",
    "CODEC_CATALOG": "voicehub.components.audio.codecs",
    "CodecCatalogEntry": "voicehub.components.audio.codecs",
    "CodecCodeBatch": "voicehub.components.audio.codecs",
    "CodecIntegration": "voicehub.components.audio.codecs",
    "CodecRepresentation": "voicehub.components.audio.codecs",
    "CodecStageAvailability": "voicehub.components.audio.codecs",
    "DenseCodecCodes": "voicehub.components.audio.codecs",
    "RaggedCodecCodes": "voicehub.components.audio.codecs",
    "codec_is_stochastic_vae": "voicehub.components.audio.codecs",
    "codec_target_is_stochastic": "voicehub.components.audio.codecs",
    "coerce_codec_codes": "voicehub.components.audio.codecs",
    "get_codec_entries_for_model": "voicehub.components.audio.codecs",
    "get_codec_entry": "voicehub.components.audio.codecs",
    "list_codec_entries": "voicehub.components.audio.codecs",
    "separate_audio_codec": "voicehub.components.audio.codecs",
    "CodecCUDAGraphCaptureError": "voicehub.optimization",
    "CodecCUDAGraphRunner": "voicehub.optimization",
    "CodecCompileComponent": "voicehub.optimization",
    "CodecCompilePolicy": "voicehub.optimization",
    "CodecKernelBackend": "voicehub.optimization",
    "CodecKernelPass": "voicehub.optimization",
    "CodecOptimizationCompatibilityError": "voicehub.optimization",
    "CodecOptimizationConfig": "voicehub.optimization",
    "CodecOptimizationPlan": "voicehub.optimization",
    "CodecOptimizationPolicy": "voicehub.optimization",
    "CodecOptimizationResult": "voicehub.optimization",
    "DiffusionArchitectureKind": "voicehub.optimization",
    "DiffusionCacheConfig": "voicehub.optimization",
    "DiffusionCachePass": "voicehub.optimization",
    "DiffusionCachePolicy": "voicehub.optimization",
    "DiffusionCachePredictor": "voicehub.optimization",
    "DiffusionCacheRefreshPolicy": "voicehub.optimization",
    "DiffusionCacheStepPolicy": "voicehub.optimization",
    "DiffusionCacheMethod": "voicehub.optimization",
    "DiffusionGuidanceStrategy": "voicehub.optimization",
    "DiffusionModelOptimizationSupport": "voicehub.optimization",
    "DiffusionOperation": "voicehub.optimization",
    "DiffusionPredictionCacheMethod": "voicehub.optimization",
    "DiffusionSamplingConfig": "voicehub.optimization",
    "DiffusionSamplingController": "voicehub.optimization",
    "DiffusionSamplingPass": "voicehub.optimization",
    "DiffusionSamplingPolicy": "voicehub.optimization",
    "DiffusionScheduleStrategy": "voicehub.optimization",
    "DiffusionSolverStrategy": "voicehub.optimization",
    "DiffusionStepContext": "voicehub.optimization",
    "STORK2FlowSolver": "voicehub.optimization",
    "STORKFlowConfig": "voicehub.optimization",
    "DiffusionServingBackend": "voicehub.diffusion_serving",
    "DiffusionServingCapability": "voicehub.diffusion_serving",
    "DiffusionServingCompatibilityError": "voicehub.diffusion_serving",
    "DiffusionTTSServingPlan": "voicehub.diffusion_serving",
    "VLLMOmniDiffusionPlugin": "voicehub.diffusion_serving",
    "VLLMOmniFeatureStatus": "voicehub.diffusion_serving",
    "bridge_vllm_omni_tts_config": "voicehub.diffusion_serving",
    "detect_vllm_omni_features": "voicehub.diffusion_serving",
    "diffusion_cache_request": "voicehub.optimization",
    "diffusion_cache_summary": "voicehub.optimization",
    "get_diffusion_serving_capability": "voicehub.diffusion_serving",
    "list_diffusion_serving_capabilities": "voicehub.diffusion_serving",
    "resolve_diffusion_tts_backend": "voicehub.diffusion_serving",
    "capture_codec_cuda_graph": "voicehub.optimization",
    "discover_codec_compile_targets": "voicehub.optimization",
    "get_diffusion_model_optimization_support": "voicehub.optimization",
    "list_diffusion_model_optimization_support": "voicehub.optimization",
    "optimize_codec": "voicehub.optimization",
    "resolve_codec_optimization": "voicehub.optimization",
    "reset_diffusion_cache_metrics": "voicehub.optimization",
}

__all__ = [
    "AcousticTrainingAdapter",
    "ALL_MODEL_TRAINING_SPECS",
    "ASRDataArchitecture",
    "ASRDataReadiness",
    "ASRDataset",
    "ASRDatasetSpec",
    "ASRInferenceConfig",
    "ASROutput",
    "ASRSegment",
    "ASRWord",
    "ASRRecordVariant",
    "AudioAutoencoderView",
    "AudioClassificationTrainingAdapter",
    "AudioCodec",
    "AudioCodecComponentView",
    "AudioFieldSchema",
    "AudioInput",
    "AudioProcessor",
    "AutoConfig",
    "AutoInferenceModel",
    "AutoModelForSpeechRecognition",
    "AutoModelForTextToSpeech",
    "AutoModelForVoiceActivityDetection",
    "AutoProcessor",
    "AutoTrainingAdapter",
    "BaseTrainingAdapter",
    "BatchFeature",
    "CausalLMTrainingAdapter",
    "CompositeTrainingAdapter",
    "CTCTrainingAdapter",
    "CodecCUDAGraphCaptureError",
    "CodecCUDAGraphRunner",
    "CODEC_CATALOG",
    "CodecCatalogEntry",
    "CodecCodeBatch",
    "CodecCompileComponent",
    "CodecCompilePolicy",
    "CodecIntegration",
    "CodecKernelBackend",
    "CodecKernelPass",
    "CodecOptimizationCompatibilityError",
    "CodecOptimizationConfig",
    "CodecOptimizationPlan",
    "CodecOptimizationPolicy",
    "CodecOptimizationResult",
    "CodecRepresentation",
    "CodecStageAvailability",
    "DataCollatorForAudioTraining",
    "DataCollatorForTTSTraining",
    "DefaultDataCollator",
    "DenseCodecCodes",
    "DiffusionArchitectureKind",
    "DiffusionCacheConfig",
    "DiffusionCachePass",
    "DiffusionCacheMethod",
    "DiffusionCachePolicy",
    "DiffusionCachePredictor",
    "DiffusionCacheRefreshPolicy",
    "DiffusionCacheStepPolicy",
    "DiffusionGuidanceStrategy",
    "DiffusionModelOptimizationSupport",
    "DiffusionOperation",
    "DiffusionPredictionCacheMethod",
    "DiffusionSamplingConfig",
    "DiffusionSamplingController",
    "DiffusionSamplingPass",
    "DiffusionSamplingPolicy",
    "DiffusionScheduleStrategy",
    "DiffusionStepContext",
    "DiffusionSolverStrategy",
    "DiffusionServingBackend",
    "DiffusionServingCapability",
    "DiffusionServingCompatibilityError",
    "DiffusionTTSServingPlan",
    "DiffusionTrainingPair",
    "DiffusionTTSOptimizationConfig",
    "EarlyStoppingCallback",
    "EpochGroupedBatchSampler",
    "EpochLengthBatchSampler",
    "EagerInferenceStrategy",
    "EvalPrediction",
    "FlowMatchingTrainingAdapter",
    "FrameClassificationTrainingAdapter",
    "IntervalStrategy",
    "LLMBackend",
    "LLMBackendCompatibilityError",
    "LLMBackendConfig",
    "LLMBackendError",
    "LLMBackendRequestError",
    "LLMBackendSupport",
    "LLMBackendTransport",
    "LLMTTSOptimizationConfig",
    "InferenceStrategy",
    "TorchCompileInferenceStrategy",
    "ModelLicenseSpec",
    "ModelSpec",
    "OptimizationCompileTarget",
    "OptimizationCompileTargetProvider",
    "OptimizationModuleRoot",
    "OptimizationModuleRootProvider",
    "OptimizationRuntimeProtocol",
    "ModelTrainingSpec",
    "OptimizerBundle",
    "OptionalDependencyError",
    "PredictionOutput",
    "PreTrainedASRModel",
    "PreTrainedAudioModel",
    "PreTrainedSpeechModel",
    "PreTrainedTTSModel",
    "PreTrainedVADModel",
    "RNNTTrainingAdapter",
    "RaggedCodecCodes",
    "SchedulerType",
    "SchedulerBundle",
    "Seq2SeqTrainingAdapter",
    "SourceLicenseError",
    "SpeechInferenceConfig",
    "SpeechSegment",
    "SpeechSeq2SeqTrainingAdapter",
    "SpeechDataset",
    "SpeechTask",
    "SpeechTrainingOutput",
    "STORK2FlowSolver",
    "STORKFlowConfig",
    "TDTTrainingAdapter",
    "TTSDataArchitecture",
    "TTSBatchingConfig",
    "TTSBatchingStrategy",
    "TTSDataReadiness",
    "TTSDataset",
    "TTSDatasetSpec",
    "TTSGenerationConfig",
    "TTSFieldSchema",
    "TTSAttentionImplementation",
    "TTSCompilePolicy",
    "TTSKernelBackend",
    "TTSOutput",
    "TTSRecordVariant",
    "TTSOptimizationCompatibilityError",
    "TTSOptimizationConfig",
    "TTSOptimizationDecision",
    "TTSOptimizationPlan",
    "TTSOptimizationProfile",
    "TTSOptimizationResult",
    "TTSOptimizationSupport",
    "TTSTrainingOutput",
    "TTSTrainingOptimizationProfile",
    "TorchTrainingStrategy",
    "TokenGenerationRequest",
    "TokenGenerationResult",
    "Trainer",
    "TrainerCallback",
    "TrainerControl",
    "TrainerState",
    "TrainingArguments",
    "TrainingContext",
    "TrainingFamily",
    "TrainingPhaseKind",
    "TrainingPhaseSpec",
    "TrainingRecipeKind",
    "TrainingStrategy",
    "TrainingSupport",
    "TrainOutput",
    "UnknownModelError",
    "UpstreamNativeTrainingAdapter",
    "VADInferenceConfig",
    "VADOutput",
    "VADSegment",
    "VoiceHubConfig",
    "VoiceHubError",
    "VoiceHubProcessor",
    "VITSTrainingAdapter",
    "VITSDiscriminatorLoss",
    "VITSCUDAGraphPolicy",
    "VITSArchitectureKind",
    "VITSModelOptimizationSupport",
    "VITSOptimizationConfig",
    "VLLMOmniDiffusionPlugin",
    "VLLMOmniFeatureStatus",
    "WandbCallback",
    "__version__",
    "build_diffusion_training_pair",
    "build_flow_matching_training_pair",
    "bridge_vllm_omni_tts_config",
    "capture_codec_cuda_graph",
    "codec_is_stochastic_vae",
    "codec_target_is_stochastic",
    "coerce_codec_codes",
    "diffusion_tts_acceleration_plan",
    "diffusion_cache_request",
    "diffusion_cache_summary",
    "discover_codec_compile_targets",
    "default_data_collator",
    "detect_vllm_omni_features",
    "get_model_spec",
    "get_last_checkpoint",
    "get_llm_backend_support",
    "get_inference_strategy",
    "get_asr_dataset_spec",
    "get_codec_entries_for_model",
    "get_codec_entry",
    "get_diffusion_model_optimization_support",
    "get_diffusion_serving_capability",
    "get_training_strategy",
    "get_training_spec",
    "get_tts_dataset_spec",
    "get_tts_optimization_config",
    "get_tts_optimization_support",
    "get_vits_model_optimization_support",
    "get_tts_training_optimization_profile",
    "list_inference_strategies",
    "list_diffusion_model_optimization_support",
    "list_diffusion_serving_capabilities",
    "list_llm_backend_support",
    "list_asr_dataset_specs",
    "list_codec_entries",
    "list_model_specs",
    "list_training_specs",
    "list_training_strategies",
    "list_tts_dataset_specs",
    "list_tts_optimization_support",
    "list_vits_model_optimization_support",
    "llm_tts_acceleration_plan",
    "load_audio",
    "masked_diffusion_regression_loss",
    "multi_codebook_cross_entropy",
    "optimize_codec",
    "register_inference_strategy",
    "register_model_alias",
    "register_model_spec",
    "register_training_alias",
    "register_training_spec",
    "register_training_strategy",
    "resolve_codec_optimization",
    "reset_diffusion_cache_metrics",
    "resolve_diffusion_tts_backend",
    "resolve_tts_optimization",
    "separate_audio_codec",
    "set_seed",
    "unregister_inference_strategy",
    "unregister_model_alias",
    "unregister_model_spec",
    "unregister_training_alias",
    "unregister_training_spec",
    "unregister_training_strategy",
    "vits_discriminator_loss",
    "vits_feature_matching_loss",
    "vits_generator_adversarial_loss",
    "vits_kl_loss",
    "vits_acceleration_plan",
]


def __getattr__(name: str):
    module_name = _LAZY_ROOT_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
