#!/usr/bin/env python3
"""Generate one concise page and sidebar link for every documented optimization."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPOSITORY_ROOT))
sys.path.insert(0, str(SCRIPTS_ROOT))

from documentation_references import OPTIMIZATION_GUIDES, OptimizationGuide, Reference  # noqa: E402

from voicehub.optimization import OPTIMIZATION_PASSES  # noqa: E402

PAGE_DIR = REPOSITORY_ROOT / "docs" / "optimizations"
SITE_CONFIG_PATH = REPOSITORY_ROOT / "mkdocs.yml"
GENERATOR_PATH = "scripts/generate_optimization_pages.py"
NAVIGATION_START = "      # BEGIN GENERATED OPTIMIZATION GUIDE NAVIGATION"
NAVIGATION_END = "      # END GENERATED OPTIMIZATION GUIDE NAVIGATION"
PAGE_SECTIONS = ("Use", "Support", "Paper and GitHub", "Verify")


def _reference_links(references: tuple[Reference, ...]) -> str:
    return "; ".join(f"[{reference.title}]({reference.url})" for reference in references)


def _implementation_link(path: str) -> str:
    return f"[VoiceHub implementation](https://github.com/kadirnar/voicehub/blob/main/{path})"


def _code_language(guide: OptimizationGuide) -> str:
    source = guide.usage.lstrip()
    return "bash" if source.startswith(("git ", "python -m pip")) else "python"


def render_page(guide: OptimizationGuide) -> str:
    """Render one code-first optimization guide."""
    pass_rows = ""
    if guide.registry_name is not None:
        pass_rows = f'''| Registry name | `{guide.registry_name}` |
| Pass ID | `{guide.pass_id}` |
| Pass version | `{guide.pass_version}` |
| Restore | `model.restore_optimization_plan(mode="inference")` |'''
    else:
        pass_rows = "| Registry name | Not registered; do not report this backend as an applied VoiceHub pass |"

    papers = _reference_links(guide.papers) if guide.papers else (
        "No dedicated upstream research paper is published for this integration.")
    github = _reference_links(guide.github)
    implementation = (
        _implementation_link(guide.implementation) if guide.implementation is not None else
        "No VoiceHub pass implementation; use the external source project directly.")
    boundary = (
        "Unsupported model, backend, transport, or checkpoint combinations fail before a request.\n"
        "The external server is a serving topology, not an applied VoiceHub optimization pass."
        if guide.group == "Serving backends" else
        "Unsupported explicit configurations must fail before mutation. A pass that\n"
        "does not match a model reports `not-applicable`; it is not an acceleration.")
    verification = (
        "Compare native and external serving with the same checkpoint, input, seed, and output\n"
        "settings. Record latency, memory, audio quality, and both exact source revisions."
        if guide.group == "Serving backends" else
        "Compare the eager and optimized paths with the same checkpoint, input, seed,\n"
        "warm-up, device, and dtype. Record latency, memory, output quality, the exact\n"
        "source revision, and the optimization manifest.")
    source_install = ""
    if guide.source_install is not None:
        source_install = f'''Install the engine from source in a separate environment:

```bash
{guide.source_install}
```

'''
    return f'''---
description: Usage, support boundaries, paper, and source links for {guide.title}.
---

# {guide.title}

{guide.summary}

## Use

{source_install}```{_code_language(guide)}
{guide.usage}
```

## Support

| Property | Value |
| --- | --- |
| Availability | {guide.availability} |
| Fidelity | {guide.fidelity} |
| Runtime | {guide.devices} |
{pass_rows}

{boundary}

## Paper and GitHub

- **Paper:** {papers}
- **Upstream GitHub:** {github}
- **VoiceHub source:** {implementation}

## Verify

{verification}

See the [related workflow]({guide.related_guide}) and
[optimization API](../reference/api.md#optimization).
'''


def render_index(guides: tuple[OptimizationGuide, ...]) -> str:
    """Render the generated optimization catalog."""
    lines = [
        "---",
        "description: Dedicated guides for every VoiceHub optimization pass and optional source backend.",
        "---",
        "",
        "# Optimization catalog",
        "",
        "Each optimization has one short page with executable code, support boundaries,",
        "research references, and upstream GitHub source.",
        "",
        f"Generated by `{GENERATOR_PATH}`.",
        "",
    ]
    for group in tuple(dict.fromkeys(guide.group for guide in guides)):
        lines.extend((
            f"## {group}",
            "",
            "| Optimization | Availability | Paper | GitHub |",
            "| --- | --- | --- | --- |",
        ))
        for guide in (item for item in guides if item.group == group):
            paper = "Available" if guide.papers else "No dedicated paper"
            lines.append(
                f"| [{guide.title}]({guide.slug}.md) | {guide.availability} | "
                f"{paper} | {_reference_links(guide.github)} |")
        lines.append("")
    return "\n".join(lines)


def render_navigation(guides: tuple[OptimizationGuide, ...]) -> str:
    """Render a flat list of clickable optimization links in the sidebar."""
    lines = [NAVIGATION_START, "      - Optimization catalog: optimizations/index.md"]
    lines.extend(f'      - "{guide.title}": optimizations/{guide.slug}.md' for guide in guides)
    lines.append(NAVIGATION_END)
    return "\n".join(lines)


def render_site_config(guides: tuple[OptimizationGuide, ...]) -> str:
    """Replace the generated optimization navigation block."""
    source = SITE_CONFIG_PATH.read_text(encoding="utf-8")
    if source.count(NAVIGATION_START) != 1 or source.count(NAVIGATION_END) != 1:
        raise RuntimeError("mkdocs.yml must contain exactly one generated optimization navigation block")
    prefix, remainder = source.split(NAVIGATION_START, 1)
    _, suffix = remainder.split(NAVIGATION_END, 1)
    return f"{prefix}{render_navigation(guides)}{suffix}"


def _validate_contract(guides: tuple[OptimizationGuide, ...]) -> None:
    slugs = tuple(guide.slug for guide in guides)
    if len(slugs) != len(set(slugs)):
        raise RuntimeError("Optimization guide slugs must be unique")
    registered = set(OPTIMIZATION_PASSES.list())
    documented = {guide.registry_name for guide in guides if guide.registry_name is not None}
    if documented != registered:
        missing = sorted(registered - documented)
        unknown = sorted(documented - registered)
        raise RuntimeError(f"Optimization reference coverage mismatch: missing={missing}, unknown={unknown}")
    for guide in guides:
        if not guide.github:
            raise RuntimeError(f"{guide.slug} must link at least one upstream GitHub repository")
        if guide.source_install is not None and not guide.source_install.startswith("git clone "):
            raise RuntimeError(f"{guide.slug} source installation must start with a Git checkout")
        if guide.registry_name is not None and not all((
                guide.pass_id,
                guide.pass_version,
                guide.implementation,
        )):
            raise RuntimeError(f"Registered pass {guide.slug} has incomplete documentation metadata")


def generated_files() -> dict[Path, str]:
    """Return all expected generated paths and contents."""
    guides = tuple(OPTIMIZATION_GUIDES)
    _validate_contract(guides)
    files = {PAGE_DIR / f"{guide.slug}.md": render_page(guide) for guide in guides}
    files[PAGE_DIR / "index.md"] = render_index(guides)
    files[SITE_CONFIG_PATH] = render_site_config(guides)
    return files


def check_generated_files(files: dict[Path, str]) -> tuple[Path, ...]:
    """Return missing, stale, or unexpected generated paths."""
    expected = set(files)
    stale = [
        path for path, content in files.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]
    if PAGE_DIR.is_dir():
        stale.extend(path for path in PAGE_DIR.glob("*.md") if path not in expected)
    return tuple(stale)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when generated optimization pages are missing or stale.",
    )
    args = parser.parse_args()
    files = generated_files()
    stale = check_generated_files(files)
    if args.check:
        if stale:
            for path in stale:
                print(f"stale: {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
            return 1
        print(f"OK: {len(OPTIMIZATION_GUIDES)} optimization pages and navigation are current")
        return 0

    PAGE_DIR.mkdir(parents=True, exist_ok=True)
    expected = set(files)
    for path in tuple(PAGE_DIR.glob("*.md")):
        if path not in expected:
            path.unlink()
            print(f"removed: {path.relative_to(REPOSITORY_ROOT)}")
    for path, content in files.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote: {path.relative_to(REPOSITORY_ROOT)}")
    print(f"OK: {len(OPTIMIZATION_GUIDES)} optimization pages and navigation")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
